// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceRule) DeepCopyInto(out *FaultToleranceRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceRule.
func (in *FaultToleranceRule) DeepCopy() *FaultToleranceRule {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultToleranceRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceRuleList) DeepCopyInto(out *FaultToleranceRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FaultToleranceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceRuleList.
func (in *FaultToleranceRuleList) DeepCopy() *FaultToleranceRuleList {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FaultToleranceRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceRuleSpec) DeepCopyInto(out *FaultToleranceRuleSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]FaultToleranceTargetRef, len(*in))
		copy(*out, *in)
	}
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]FaultToleranceStrategyRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceRuleSpec.
func (in *FaultToleranceRuleSpec) DeepCopy() *FaultToleranceRuleSpec {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceRuleStatus) DeepCopyInto(out *FaultToleranceRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceRuleStatus.
func (in *FaultToleranceRuleStatus) DeepCopy() *FaultToleranceRuleStatus {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceStrategyRef) DeepCopyInto(out *FaultToleranceStrategyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceStrategyRef.
func (in *FaultToleranceStrategyRef) DeepCopy() *FaultToleranceStrategyRef {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceStrategyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultToleranceTargetRef) DeepCopyInto(out *FaultToleranceTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultToleranceTargetRef.
func (in *FaultToleranceTargetRef) DeepCopy() *FaultToleranceTargetRef {
	if in == nil {
		return nil
	}
	out := new(FaultToleranceTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStrategy) DeepCopyInto(out *RateLimitStrategy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStrategy.
func (in *RateLimitStrategy) DeepCopy() *RateLimitStrategy {
	if in == nil {
		return nil
	}
	out := new(RateLimitStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitStrategy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStrategyList) DeepCopyInto(out *RateLimitStrategyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimitStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStrategyList.
func (in *RateLimitStrategyList) DeepCopy() *RateLimitStrategyList {
	if in == nil {
		return nil
	}
	out := new(RateLimitStrategyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitStrategyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStrategySpec) DeepCopyInto(out *RateLimitStrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStrategySpec.
func (in *RateLimitStrategySpec) DeepCopy() *RateLimitStrategySpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStrategyStatus) DeepCopyInto(out *RateLimitStrategyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStrategyStatus.
func (in *RateLimitStrategyStatus) DeepCopy() *RateLimitStrategyStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitStrategyStatus)
	in.DeepCopyInto(out)
	return out
}
